### ISSUE TITLE
Installation error for 0.6.3

### ISSUE THREAD

**Issue by oneautomate** [iamseth/python-zenoss#14]
Hi There,
as of today, 11/09/2016, I have problem installing the package.
using pip failed at copying 'LICENSE.txt' :
........

running install_data

error: can't copy 'LICENSE.txt': doesn't exist or not a regular file

----------------------------------------
Cleaning up...
Command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/zenoss/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vH0qAV-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/zenoss
Storing debug log for failure in /root/.pip/pip.log

Manual install -- 
running install_data
error: can't copy 'list_devices.py': doesn't exist or not a regular file

workaround:
I have to modify the 'setup.py' file with below change, then manual install succeeded:
From:
data_files = [('', ['LICENSE.txt']),('', ['README.md']),('examples', ['list_devices.py']),]
To:
data_files = [('', ['LICENSE.txt']),('', ['README.md']),('examples','', ['list_devices.py']),]

Can you please fix the installation issue?

**Comment by oneautomate** [comment]
I tried on Windows 10 and Amazon Linux, both failed with the same error.

**Comment by sandrotosi** [comment]
the problem is that the files declared in data_files are missing from the pypi released tarball, so setup.py cant find them if you're using that tarball.

for now i skipped them in the debian package using this patch https://anonscm.debian.org/cgit/python-modules/packages/python-zenoss.git/diff/debian/patches/skip_missing_files.patch?id=d8f34202c5d100a5203d8c2c0907af8115af0260 but it would be great if they'd be included in the tarball (as they are indeed useful to have and install!)

thanks

**Comment by iamseth** [comment]
This is no longer an actively maintained project. See README.
