### ISSUE TITLE
json error message - ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ebailey1367** [iamseth/python-zenoss#7]
error message using example function to list all devices in Zenoss

[test@xxxxx bin]$ ./zenoss_test.py 
Traceback (most recent call last):
  File "./zenoss_test.py", line 7, in <module>
    for device in zenoss.get_devices()['devices']:
  File "/usr/lib/python2.6/site-packages/zenoss-0.6.2-py2.6.egg/zenoss.py", line 90, in get_devices
    data=[{'uid': device_class, 'params': {}, 'limit': limit}])
  File "/usr/lib/python2.6/site-packages/zenoss-0.6.2-py2.6.egg/zenoss.py", line 68, in __router_request
    return json.loads(response.content.decode("utf-8"))['result']
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

RPS and version installed

Product: zenoss-resmgr-4.2.4 (id = zenoss-resmgr-4.2.4)
Home: /opt/zenoss
Revision: 863
Upgrading: None
Minimum: 863
Updated On: Thu Mar 10 09:06:40 2016

Would really like to use your package since it looks super useful. Any idea what this means?

Thanks

Ed

**Comment by iamseth** [comment]
Ed, looks like Zenoss is returning something this library isn't expecting. I can't tell from the output but if you attached a debugger or added a print statement for this

response.content.decode("utf-8")

you'll be able to see what Zenoss is sending back. It's probably an error in HTML as opposed to JSON that the library is expecting. Why Zenoss is doing that isn't clear to me.

It's going to sound like a stupid hack but you might try restarting Zenoss if you haven't already. If I recall correctly I've seen this before and restarting "solved" it. Unfortunately I don't use Zenoss anymore or this library so that's all I got.
